import { parseAbi, parseAbiItem } from "viem";

/**
 * Event signatures the indexer subscribes to.
 *
 * These must stay byte-identical to `contracts/abis/events.json` (regenerated by
 * `npm run abis` in the contracts package). `verifyChainConstants()` in src/chain.ts calls the
 * deployed factory on startup and refuses to run if the on-chain constants disagree with
 * `PROTOCOL`, which catches an ABI/deployment mismatch before any bad data is written.
 */
export const FACTORY_EVENTS = parseAbi([
  "event TokenCreated(address indexed token, address indexed creator, string name, string symbol, uint256 totalSupply, uint256 virtualEthReserve, uint256 virtualTokenReserve, uint256 migrationThreshold, uint256 timestamp)",
  "event TokenBought(address indexed token, address indexed buyer, uint256 ethIn, uint256 fee, uint256 ethAfterFee, uint256 tokensOut, uint256 tokenPrice, uint256 ethReserve, uint256 virtualEthReserve, uint256 tokenReserve, uint256 timestamp)",
  "event TokenSold(address indexed token, address indexed seller, uint256 tokensIn, uint256 grossEthOut, uint256 fee, uint256 ethOut, uint256 tokenPrice, uint256 ethReserve, uint256 virtualEthReserve, uint256 tokenReserve, uint256 timestamp)",
  "event MigrationTriggered(address indexed token, uint256 ethReserve, uint256 tokenReserve, uint256 timestamp)",
  "event LiquidityMigrated(address indexed token, address indexed pair, uint256 ethAmount, uint256 tokenAmount, uint256 tokensBurned, uint256 lpTokensBurned, uint256 timestamp)",
  "event PlatformFeeCollected(address indexed token, address indexed user, uint8 indexed action, uint256 amount, uint256 timestamp)",
]);

export const TRANSFER_EVENT = parseAbiItem(
  "event Transfer(address indexed from, address indexed to, uint256 value)",
);

/** Read-only factory surface used for startup validation and API fallbacks. */
export const FACTORY_VIEW_ABI = parseAbi([
  "function allTokensLength() view returns (uint256)",
  "function allTokens(uint256) view returns (address)",
  "function TOTAL_SUPPLY() view returns (uint256)",
  "function VIRTUAL_ETH_RESERVE() view returns (uint256)",
  "function MIGRATION_THRESHOLD() view returns (uint256)",
  "function BUY_FEE_BPS() view returns (uint256)",
  "function SELL_FEE_BPS() view returns (uint256)",
]);
