// Keeps subgraph/abis in sync with the ABIs generated by the contracts package, so a contract
// change can never leave the subgraph decoding against a stale event signature.
const fs = require("fs");
const path = require("path");

const source = path.join(__dirname, "..", "..", "contracts", "abis");
const destination = path.join(__dirname, "..", "abis");

if (!fs.existsSync(source)) {
  console.error(`Missing ${source}. Run \`npm run abis\` in the contracts package first.`);
  process.exit(1);
}

fs.mkdirSync(destination, { recursive: true });

for (const name of ["PumperFactory.json", "PumperToken.json"]) {
  const from = path.join(source, name);
  if (!fs.existsSync(from)) {
    console.error(`Missing ${from}. Run \`npm run abis\` in the contracts package first.`);
    process.exit(1);
  }
  fs.copyFileSync(from, path.join(destination, name));
  console.log(`copied ${name}`);
}
